version: '3.7'

services:

  contacts.api:
    image: nibro7778/contacts.api
    build:
      context: .
      dockerfile: src/Services/Contacts Service/Contacts.API/Dockerfile
    ports:
      - '5001:80'