version: '3.7'

services:
  teamcity:
    image: jetbrains/teamcity-server:latest
    volumes:
      - teamcity-server-datadir:/data/teamcity_server/datadir
      - teamcity-server-logs:/opt/teamcity/logs
    ports:
      - 8111:8111
  teamcity-agent:
    image: jetbrains/teamcity-agent:latest
    environment:
      SERVER_URL: http://teacity:8111
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  teamcity-server-datadir:
  teamcity-server-logs:
